version: '3'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile-FastAPI
    ports:
      - "8000:80"
    depends_on:
      - flask-app

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile-Flask
    ports:
      - "5000:5000"
    depends_on:
      - fastapi-app
